<table width="100%">
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
    <tr>
        <td colspan="2"><strong><?php _e('General options', 'mss_widget_domain'); ?></strong></td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td width="20%"><?php _e('Title', 'mss_widget_domain'); ?></td>
        <td>
            <input class="widefat" id="<?php echo $this->get_field_id('title'); ?>" 
                   name="<?php echo $this->get_field_name('title'); ?>" 
                   type="text" value="<?php echo $instance['title']; ?>">
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td width="20%"><?php _e('Host', 'mss_widget_domain'); ?></td>
        <td>
            <input class="widefat" id="<?php echo $this->get_field_id('host'); ?>" 
                   name="<?php echo $this->get_field_name('host'); ?>" 
                   type="text" value="<?php echo $instance['host']; ?>">
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td width="20%"><?php _e('Port', 'mss_widget_domain'); ?></td>
        <td>
            <input class="widefat" id="<?php echo $this->get_field_id('port'); ?>" 
                   name="<?php echo $this->get_field_name('port'); ?>" 
                   type="text" value="<?php echo $instance['port']; ?>">
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>

<table width="100%">
    <tr>
        <td colspan="2"><strong><?php _e('Display options', 'mss_widget_domain'); ?></strong></td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td><?php _e('Show status', 'mss_widget_domain'); ?></td>
        <td style="text-align:right;">
            <input id="<?php echo $this->get_field_id('show_status'); ?>" 
                   name="<?php echo $this->get_field_name('show_status'); ?>" 
                   type="checkbox" value="on" <?php echo ($instance['show_status'] == 'on') ? 'checked="checked"' : ''; ?>>
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td><?php _e('Show host', 'mss_widget_domain'); ?></td>
        <td style="text-align:right;">
            <input id="<?php echo $this->get_field_id('show_host'); ?>" 
                   name="<?php echo $this->get_field_name('show_host'); ?>" 
                   type="checkbox" value="on" <?php echo ($instance['show_host'] == 'on') ? 'checked="checked"' : ''; ?>>
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td><?php _e('Show port', 'mss_widget_domain'); ?></td>
        <td style="text-align:right;">
            <input id="<?php echo $this->get_field_id('show_port'); ?>" 
                   name="<?php echo $this->get_field_name('show_port'); ?>" 
                   type="checkbox" value="on" <?php echo ($instance['show_port'] == 'on') ? 'checked="checked"' : ''; ?>>
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <tr>
        <td><?php _e('Show ping', 'mss_widget_domain'); ?></td>
        <td style="text-align:right;">
            <input id="<?php echo $this->get_field_id('show_ping'); ?>" 
                   name="<?php echo $this->get_field_name('show_ping'); ?>" 
                   type="checkbox" value="on" <?php echo ($instance['show_ping'] == 'on') ? 'checked="checked"' : ''; ?>>
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <!--
    <tr>
        <td><?php _e('Show plugins', 'mss_widget_domain'); ?></td>
        <td style="text-align:right;">
            <input id="<?php echo $this->get_field_id('show_plugins'); ?>" 
                   name="<?php echo $this->get_field_name('show_plugins'); ?>" 
                   type="checkbox" value="on" <?php echo ($instance['show_plugins'] == 'on') ? 'checked="checked"' : ''; ?>>
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    -->
    <tr>
        <td><?php _e('Show player count', 'mss_widget_domain'); ?></td>
        <td style="text-align:right;">
            <input id="<?php echo $this->get_field_id('show_players'); ?>" 
                   name="<?php echo $this->get_field_name('show_players'); ?>" 
                   type="checkbox" value="on" <?php echo ($instance['show_players'] == 'on') ? 'checked="checked"' : ''; ?>>
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    <!--
    <tr>
        <td><?php _e('Avatar size', 'mss_widget_domain'); ?></td>
        <td style="text-align:right;">
            <input id="<?php echo $this->get_field_id('avatar_size'); ?>" size="5" 
                   name="<?php echo $this->get_field_name('avatar_size'); ?>" 
                   type="text" value="<?php echo $instance['avatar_size']; ?>">
        </td>
    </tr>
    <tr>
        <td colspan="2"><hr class="mss"></td>
    </tr>
    -->
    <tr>
        <td colspan="2">&nbsp;</td>
    </tr>
</table>

<style>
    hr.mss {
        border:0;
        color:#D7D7D7;
        background:#D7D7D7;
        height:1px;
    }
</style>